# Generated by Django 3.1 on 2020-08-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_board_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='slug',
        ),
    ]
