# Generated by Django 3.1 on 2020-08-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor_board_app', '0002_remove_monitor_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
